import { Navbar, Footer } from "@/components";
import "./globals.css";
export const metadata = {
  title: "Shopbag",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
